kind = "web"
previewPath = "/"
title = "PDV Restaurante"
version = "1.0.0"
id = "artifacts/pdv-restaurante"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19473

[services.development]
run = "pnpm --filter @workspace/pdv-restaurante run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/pdv-restaurante", "run", "build" ]
publicDir = "artifacts/pdv-restaurante/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19473"
BASE_PATH = "/"
